name = "AziFy: Revive"
version = [0, 1, 5]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- Revamp Your Experience!
%v
§3 https://github.com/Aziangelo
''' # %w = patch warning, %v = version
authors = ["AziAngelo"]
url = "https://github.com/Aziangelo"
uuid = "177361cb-044e-483a-9ca3-52d75ab9376b" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2024 %a, and "AziFy Shader" Contributors

This compiled "AziFy Shader" resource pack (source code: https://github.com/Aziangelo/AF-Revive.git under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "AziFy Shader". Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/WcR9usdTpZ
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

